# Generated by Django 4.2.27 on 2025-12-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_country_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
